/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IFTM
 */
public class TabelaVinhos extends javax.swing.JFrame {

    /**
     * Creates new form TabelaVinhos
     */
    public TabelaVinhos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_tituloTabelaVinhos = new javax.swing.JLabel();
        jlb_buscarCliente = new javax.swing.JLabel();
        jtf_buscarCliente = new javax.swing.JTextField();
        jlb_mostrarVinhos = new javax.swing.JLabel();
        jtf_mostrarVinhos = new javax.swing.JTextField();
        jbt_buscarVInhos = new javax.swing.JButton();
        jbt_atualizaVinhos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_tituloTabelaVinhos.setText("Tabela de vinhos por cliente");

        jlb_buscarCliente.setText("Buscar cliente:");

        jtf_buscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_buscarClienteActionPerformed(evt);
            }
        });

        jlb_mostrarVinhos.setText("Mostrar vinhos vinculados:");

        jbt_buscarVInhos.setText("Buscar");
        jbt_buscarVInhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_buscarVInhosActionPerformed(evt);
            }
        });

        jbt_atualizaVinhos.setText("Atualizar");
        jbt_atualizaVinhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_atualizaVinhosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtf_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_mostrarVinhos))
                    .addComponent(jbt_buscarVInhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jlb_buscarCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlb_mostrarVinhos))
                            .addComponent(jlb_tituloTabelaVinhos, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 168, Short.MAX_VALUE))
                    .addComponent(jbt_atualizaVinhos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlb_tituloTabelaVinhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_buscarCliente)
                    .addComponent(jlb_mostrarVinhos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_buscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_mostrarVinhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_buscarVInhos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_atualizaVinhos)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_buscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_buscarClienteActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jtf_buscarClienteActionPerformed

    private void jbt_buscarVInhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_buscarVInhosActionPerformed
        // TODO add your handling code here:
        ArrayList<String> listaDeVinculos = new ArrayList<>();
        String[] textoSeparado = null;
        int idCliente;
        
        
        //Lendo o arquivo txt
        FileWriter fw = null;
        
        try {
            // TODO add your handling code here:
            
            //Gravando dados no arquivo txt
            File arquivo = new File( "C:\\Users\\IFTM\\Desktop\\IFTM\\POOV\\Vinhos\\ClienteVinho.txt" );
            boolean existe = arquivo.exists();
            System.out.println(existe);
            
            //Criando estrutura csv
            if(!existe){
                JOptionPane.showInputDialog("Arquivo procurado não existe.");
            }else{
                
                FileReader fr = new FileReader( arquivo );
                BufferedReader br = new BufferedReader( fr );
                int cont = 0;
                
                while( br.ready() ){
                    //lê a proxima linha
                    String linha = br.readLine();
                    System.out.println(linha);
                    if(cont>0){
                        listaDeVinculos.add(linha);
                    //faz algo com a linha
                    }
                    cont = cont+1;
                    
                    
                }
                
                for(int i=0;i<listaDeVinculos.size();i++){
                    textoSeparado = listaDeVinculos.get(i).split(";");
                    idCliente = Integer.parseInt(textoSeparado[0]);
                    if(idCliente==Integer.parseInt(jtf_buscarCliente.getText())){
                        jtf_mostrarVinhos.setText(textoSeparado[1]);
                    }
                }
                
                br.close();
                fr.close();
                
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbt_buscarVInhosActionPerformed

    private void jbt_atualizaVinhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_atualizaVinhosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jbt_atualizaVinhosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TabelaVinhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TabelaVinhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TabelaVinhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TabelaVinhos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TabelaVinhos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt_atualizaVinhos;
    private javax.swing.JButton jbt_buscarVInhos;
    private javax.swing.JLabel jlb_buscarCliente;
    private javax.swing.JLabel jlb_mostrarVinhos;
    private javax.swing.JLabel jlb_tituloTabelaVinhos;
    private javax.swing.JTextField jtf_buscarCliente;
    private javax.swing.JTextField jtf_mostrarVinhos;
    // End of variables declaration//GEN-END:variables
}
