/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import classes.Cliente;
import classes.Produto;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author IFTM
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlb_tituloClientes = new javax.swing.JLabel();
        jlb_idCliente = new javax.swing.JLabel();
        jlb_nomeCliente = new javax.swing.JLabel();
        jlb_email = new javax.swing.JLabel();
        jlb_telefone = new javax.swing.JLabel();
        jlb_endereco = new javax.swing.JLabel();
        jlb_tituloVinhos = new javax.swing.JLabel();
        jlb_idVinho = new javax.swing.JLabel();
        jlb_valor = new javax.swing.JLabel();
        jlb_descricao = new javax.swing.JLabel();
        jlb_tipoDaUva = new javax.swing.JLabel();
        jlb_anoDaSafra = new javax.swing.JLabel();
        jlb_quantidade = new javax.swing.JLabel();
        jlb_diaDaVenda = new javax.swing.JLabel();
        jtf_idCliente = new javax.swing.JTextField();
        jtf_nome = new javax.swing.JTextField();
        jtf_email = new javax.swing.JTextField();
        jtf_telefone = new javax.swing.JTextField();
        jtf_endereco = new javax.swing.JTextField();
        jtf_diaDaVenda = new javax.swing.JTextField();
        jtf_quantidade = new javax.swing.JTextField();
        jtf_anoDaSafra = new javax.swing.JTextField();
        jtf_tipoDaUva = new javax.swing.JTextField();
        jtf_descricao = new javax.swing.JTextField();
        jtf_valor = new javax.swing.JTextField();
        jtf_idProduto = new javax.swing.JTextField();
        jbt_cadastroCliente = new javax.swing.JButton();
        jbt_cadastroProduto = new javax.swing.JButton();
        jlb_tituloClienteVinho = new javax.swing.JLabel();
        jlb_idCliente_clienteVinho = new javax.swing.JLabel();
        jtf_idCliente_clienteVinho = new javax.swing.JTextField();
        jlb_idVinho_clienteVinho = new javax.swing.JLabel();
        jtf_idVinho_clienteVinho = new javax.swing.JTextField();
        jbt_clienteVinho = new javax.swing.JButton();
        jbt_abrirVinculos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlb_tituloClientes.setText("Cadastro de clientes");

        jlb_idCliente.setText("ID cliente:");

        jlb_nomeCliente.setText("Nome:");

        jlb_email.setText("E-mail:");

        jlb_telefone.setText("Telefone:");

        jlb_endereco.setText("Endereço:");

        jlb_tituloVinhos.setText("Cadastro de vinhos");

        jlb_idVinho.setText("ID vinho:");

        jlb_valor.setText("Valor:");

        jlb_descricao.setText("Descrição:");

        jlb_tipoDaUva.setText("Tipo da uva:");

        jlb_anoDaSafra.setText("Ano da safra:");

        jlb_quantidade.setText("Quantidade:");

        jlb_diaDaVenda.setText("Dia da venda:");

        jbt_cadastroCliente.setText("Cadrastrar cliente");
        jbt_cadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_cadastroClienteActionPerformed(evt);
            }
        });

        jbt_cadastroProduto.setText("Cadastrar produto");
        jbt_cadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_cadastroProdutoActionPerformed(evt);
            }
        });

        jlb_tituloClienteVinho.setText("Vincular cliente e vinho");

        jlb_idCliente_clienteVinho.setText("ID cliente:");

        jlb_idVinho_clienteVinho.setText("ID vinho:");

        jbt_clienteVinho.setText("Vincular cliente e vinho");
        jbt_clienteVinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_clienteVinhoActionPerformed(evt);
            }
        });

        jbt_abrirVinculos.setText("Vinculos");
        jbt_abrirVinculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt_abrirVinculosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlb_idCliente)
                                    .addComponent(jlb_nomeCliente)
                                    .addComponent(jlb_email)
                                    .addComponent(jlb_telefone))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_idCliente)
                                    .addComponent(jtf_nome)
                                    .addComponent(jtf_email)
                                    .addComponent(jtf_telefone)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlb_endereco)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbt_cadastroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jtf_endereco)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jlb_tituloClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jlb_tituloClienteVinho)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jlb_idCliente_clienteVinho)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jtf_idCliente_clienteVinho)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlb_quantidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlb_anoDaSafra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtf_anoDaSafra, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlb_tituloVinhos)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlb_tipoDaUva)
                                        .addComponent(jlb_descricao)
                                        .addComponent(jlb_valor)
                                        .addComponent(jlb_idVinho))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jtf_tipoDaUva)
                                        .addComponent(jtf_descricao)
                                        .addComponent(jtf_valor)
                                        .addComponent(jtf_idProduto)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jlb_diaDaVenda)
                                        .addComponent(jlb_idVinho_clienteVinho))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jbt_cadastroProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                        .addComponent(jtf_diaDaVenda)
                                        .addComponent(jtf_idVinho_clienteVinho))))))
                    .addComponent(jbt_clienteVinho, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbt_abrirVinculos, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_tituloClientes)
                    .addComponent(jlb_tituloVinhos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_idCliente)
                    .addComponent(jlb_idVinho)
                    .addComponent(jtf_idCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_idProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_nomeCliente)
                    .addComponent(jlb_valor)
                    .addComponent(jtf_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_email)
                    .addComponent(jlb_descricao)
                    .addComponent(jtf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_telefone)
                    .addComponent(jlb_tipoDaUva)
                    .addComponent(jtf_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_tipoDaUva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_endereco)
                    .addComponent(jlb_anoDaSafra)
                    .addComponent(jtf_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_anoDaSafra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_quantidade)
                    .addComponent(jtf_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbt_cadastroCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_diaDaVenda)
                    .addComponent(jtf_diaDaVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_cadastroProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlb_tituloClienteVinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlb_idCliente_clienteVinho)
                    .addComponent(jtf_idCliente_clienteVinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlb_idVinho_clienteVinho)
                    .addComponent(jtf_idVinho_clienteVinho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_clienteVinho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbt_abrirVinculos)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt_cadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_cadastroClienteActionPerformed
        FileWriter fw = null;
        try {
            // TODO add your handling code here:
            Cliente cliente = new Cliente();
            cliente.setIdCliente(jtf_idCliente.getText());
            cliente.setNome(jtf_nome.getText());
            cliente.setEmail(jtf_email.getText());
            cliente.setTelefone(jtf_telefone.getText());
            cliente.setEndereco(jtf_endereco.getText());
            
            //Gravando dados no arquivo txt
            File arquivo = new File( "C:\\Users\\IFTM\\Desktop\\IFTM\\POOV\\Vinhos\\Clientes.txt" );
            boolean existe = arquivo.exists();
            System.out.println(existe);
            
            //Criando estrutura csv
            if(!existe){
                fw = new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter( fw );
                //escreve o conteúdo no arquivo
                bw.write("idCliente;nome;email;telefone;endereco\n" + cliente.toString());
                bw.newLine();
            //fecha os recursos
                bw.close();
                fw.close();
                System.out.println("idCliente;nome;email;telefone;endereco\n" + cliente.toString());
            }else{
                fw = new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter( fw );
                //escreve o conteúdo no arquivo
                bw.write(cliente.toString());
                //quebra de linha
                bw.newLine();
                //fecha os recursos
                bw.close();
                fw.close();
                System.out.println(cliente.toString());
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
       
        
        
    }//GEN-LAST:event_jbt_cadastroClienteActionPerformed

    private void jbt_cadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_cadastroProdutoActionPerformed
        // TODO add your handling code here:
        FileWriter fw = null;
        try {
            // TODO add your handling code here:
            Produto produto = new Produto();
            produto.setIdProduto(jtf_idProduto.getText());
            produto.setValor(Float.parseFloat(jtf_valor.getText()));
            produto.setDescricao(jtf_descricao.getText());
            produto.setTipoDaUva(jtf_tipoDaUva.getText());
            produto.setAnoDaSafra(Integer.parseInt(jtf_anoDaSafra.getText()));
            produto.setQuantidade(Integer.parseInt(jtf_quantidade.getText()));
            produto.setDiaDaVenda(LocalDate.parse(jtf_diaDaVenda.getText()));
            
            //Gravando dados no arquivo txt
            File arquivo = new File( "C:\\Users\\IFTM\\Desktop\\IFTM\\POOV\\Vinhos\\Produtos.txt" );
            boolean existe = arquivo.exists();
            System.out.println(existe);
            
            //Criando estrutura csv
            if(!existe){
                fw = new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter( fw );
                //escreve o conteúdo no arquivo
                bw.write("idProduto;valor;descricao;tipoDaUva;anoDaSafra;quantidade;diaDaVenda\n" + produto.toString());
                bw.newLine();
            //fecha os recursos
                bw.close();
                fw.close();
                System.out.println("idCliente;nome;email;telefone;endereco\n" + produto.toString());
            }else{
                fw = new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter( fw );
                //escreve o conteúdo no arquivo
                bw.write(produto.toString());
                //quebra de linha
                bw.newLine();
                //fecha os recursos
                bw.close();
                fw.close();
                System.out.println(produto.toString());
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbt_cadastroProdutoActionPerformed

    private void jbt_clienteVinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_clienteVinhoActionPerformed
        // TODO add your handling code here:
        FileWriter fw = null;
        try {
            // TODO add your handling code here:
            
            //Gravando dados no arquivo txt
            File arquivo = new File( "C:\\Users\\IFTM\\Desktop\\IFTM\\POOV\\Vinhos\\ClienteVinho.txt" );
            boolean existe = arquivo.exists();
            System.out.println(existe);
            
            //Criando estrutura csv
            if(!existe){
                fw = new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter( fw );
                //escreve o conteúdo no arquivo
                bw.write("idCliente;idVinho\n" + jtf_idCliente_clienteVinho.getText() + ";" + jtf_idVinho_clienteVinho.getText());
                bw.newLine();
            //fecha os recursos
                bw.close();
                fw.close();
            }else{
                fw = new FileWriter(arquivo, true);
                BufferedWriter bw = new BufferedWriter( fw );
                FileReader fr = new FileReader( arquivo );
                BufferedReader br = new BufferedReader( fr );
                ArrayList<String> listaDeVinculos = new ArrayList<>();
                String[] textoSeparado;
                
                int cont = 0;
                //escreve o conteúdo no arquivo
                
                //Vai verificar se o id já está inserido
                int verificaEntrada=0; 
                //Fazendo a verificação
                while(verificaEntrada!=1){
                    while( br.ready() ){
                        
                        
                        //lê a proxima linha
                        System.out.println("Entrou2");
                        String linha = br.readLine();
                        System.out.println(linha);
                        if(cont>0){                        
                            System.out.println("Entrou3");
                            //faz algo com a linha
                            listaDeVinculos.add(linha);
                        }
                        cont = cont+1;            
                    
                    }
                    
                    for(int i=0;i<listaDeVinculos.size();i++){
                        textoSeparado = listaDeVinculos.get(i).split(";");
                        int idCliente = Integer.parseInt(textoSeparado[0]);
                        if(idCliente==Integer.parseInt(jtf_idCliente_clienteVinho.getText())){
                            JOptionPane.showInputDialog("O id do cliente já existe. Digite outro.");
                        }else{
                            verificaEntrada=1;
                        }
                    }
                    
                }              
                
                bw.write(jtf_idCliente_clienteVinho.getText() + ";" + jtf_idVinho_clienteVinho.getText());
                //quebra de linha
                bw.newLine();
                //fecha os recursos
                bw.close();
                fw.close();
            }
            
            
        } catch (IOException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbt_clienteVinhoActionPerformed

    private void jbt_abrirVinculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt_abrirVinculosActionPerformed
        // TODO add your handling code here:
        TabelaVinhos tabelaVinhos = new TabelaVinhos();
        tabelaVinhos.setVisible(true);
        tabelaVinhos.setLocationRelativeTo(null);//Para centralizar a tela
    }//GEN-LAST:event_jbt_abrirVinculosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbt_abrirVinculos;
    private javax.swing.JButton jbt_cadastroCliente;
    private javax.swing.JButton jbt_cadastroProduto;
    private javax.swing.JButton jbt_clienteVinho;
    private javax.swing.JLabel jlb_anoDaSafra;
    private javax.swing.JLabel jlb_descricao;
    private javax.swing.JLabel jlb_diaDaVenda;
    private javax.swing.JLabel jlb_email;
    private javax.swing.JLabel jlb_endereco;
    private javax.swing.JLabel jlb_idCliente;
    private javax.swing.JLabel jlb_idCliente_clienteVinho;
    private javax.swing.JLabel jlb_idVinho;
    private javax.swing.JLabel jlb_idVinho_clienteVinho;
    private javax.swing.JLabel jlb_nomeCliente;
    private javax.swing.JLabel jlb_quantidade;
    private javax.swing.JLabel jlb_telefone;
    private javax.swing.JLabel jlb_tipoDaUva;
    private javax.swing.JLabel jlb_tituloClienteVinho;
    private javax.swing.JLabel jlb_tituloClientes;
    private javax.swing.JLabel jlb_tituloVinhos;
    private javax.swing.JLabel jlb_valor;
    private javax.swing.JTextField jtf_anoDaSafra;
    private javax.swing.JTextField jtf_descricao;
    private javax.swing.JTextField jtf_diaDaVenda;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_endereco;
    private javax.swing.JTextField jtf_idCliente;
    private javax.swing.JTextField jtf_idCliente_clienteVinho;
    private javax.swing.JTextField jtf_idProduto;
    private javax.swing.JTextField jtf_idVinho_clienteVinho;
    private javax.swing.JTextField jtf_nome;
    private javax.swing.JTextField jtf_quantidade;
    private javax.swing.JTextField jtf_telefone;
    private javax.swing.JTextField jtf_tipoDaUva;
    private javax.swing.JTextField jtf_valor;
    // End of variables declaration//GEN-END:variables
}
